### ISSUE TITLE
Incorrect AS aliasing in snowplow_mobile_base_events_this_run.sql

### ISSUE THREAD

**Issue by jrpeck1989** [snowplow/dbt-snowplow-mobile#57]
## Describe the bug

In the geo context columns in the [events_this_run.sql file in Databricks](https://github.com/snowplow/dbt-snowplow-mobile/blob/main/models/base/scratch/databricks/snowplow_mobile_base_events_this_run.sql) there are 3 different erroneous `AS AS` trying to alias column names which fail to run successfully

## Screenshots and log output
![CleanShot 2023-01-11 at 15 58 51](https://user-images.githubusercontent.com/19979191/211854343-11683c93-9536-4081-9727-769b39650ea1.png)

## System information
**The contents of your `packages.yml` file:**
```yml
# contents goes here
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ x] databricks
- [ ] other (specify: ____________)

**Comment by rlh1994** [comment]
Thanks @jrpeck1989 we'll get this fixed soon!
