### ISSUE TITLE
Typo in models/base/scratch/base_scratch.yml, line 46

### ISSUE THREAD

**Issue by dkbrkjni** [snowplow/dbt-snowplow-mobile#79]
## Describe the bug
Typo in file models/base/scratch/base_scratch.yml, line 46: `screescreen_top_view_controllern_type`

## Screenshots and log output
![image](https://github.com/snowplow/dbt-snowplow-mobile/assets/14215821/60c8914d-5176-41e4-98d8-c992df5b306f)

## System information
**The contents of your `packages.yml` file:**
```yml
# contents goes here
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] databricks
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by rlh1994** [comment]
Hi @dkbrkjni, we're in the process of a new release for mobile, we'll make sure these fixes are included in that release.
